a = input('Digite algo')
print ('O tipo primitivo desse valor é: ', type(a))
print('So tem espaços? ', a.isspace())
print('É alfabetico?', a.isalpha())
print('É numeral?', a.isnumeric())
print('É alfanumerico?', a.isalnum())
print('Esta em maiusculas?', a.isupper())
print('Esta em minuscula?', a.islower())
print('Esta capitalizada?', a.istitle())